name: Nextcloud setup

on:
  push:
    paths:
      - '**setup-nextcloud**'
      - 'package.json'
      - 'package-lock.json'
      - 'node_modules/**'

jobs:
  setup-nextcloud:
    runs-on: ubuntu-latest
    env:
      FILENAME: ".revision"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Script test
        uses: ./setup-nextcloud/
        with:
          version: '19'
          cron: true
          database-type: 'sqlite'
      - name: Test setup
        run: cd server && ./occ maintenance:mode --on